refs #11111 changes

diff --git a/ci-test b/ci-test
--- a/ci-test
+++ b/ci-test
@@ -1,3 +1,3 @@
 echo 'successful develop'
-
-exit 0
+echo '++ fail feature-11111'
+exit 666
